# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcdf0a9e820f6066a786f1f31d8b403686acbb35f528067bacd79d96e44ed3961207f2a5b1d1d5c6894eb617af13eae1d8a326b915e357008ec5b02c7b80ff9

test:
  secret_key_base: e55bc4b3d5d08906d41f419781de7ab8fad9ced847b0f30c01cff3da46fba5bf575d71a22cb1ca63fc8d9a077846298038f94cfdd2270e4dcdcf1c6bc8ebbce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
